server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/heima?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        max-wait: 10000 # 连接等待时间
  jackson:
    default-property-inclusion: non_null # JSON?????????
mybatis-plus:
  type-aliases-package: com.tl.dianping.entity # ?????
logging:
  level:
    com.tl.dianping: debug
  pattern:
    dateformat: mm:ss.SSS
