server:
  port: 8081
logging:
  level:
    com.example: info
  pattern:
    dateformat: HH:mm:ss:SSS
spring:
  redis:
    sentinel:
      master: mymaster
#      master:mymaster #指定master名称
      nodes: #指定redis-sentienl集群信息
        - 127.0.0.1:26379
        - 127.0.0.1:26380
        - 127.0.0.1:26381

